data-source:
  mysql:
    url: jdbc:mysql://127.0.0.1:3306/peanut?serverTimezone=UTC
    username: root
    password: xuyangliu99.
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.5.162
    port: 6379
    database: 0
    max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 100 # 连接池中的最大空闲连接
    min-idle: 50 # 连接池中的最小空闲连接
    max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    scheme: http
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
